language: java
sudo: false
script: mvn install
deploy:
  provider: releases
  api_key:
    secure: OsxkhnilDy5tBtFKbZ5NlrFJOwOaQzTL499MT9qLEo7tq7a2+0V4yQV849jaAYa4qPlNor6CbgFtEQhjOyr7zhQ0jWc/feI3zwvwv3jPUQxiEAO3ob3gc7bMMfu9UYrArgBMh6d7nh13u2J+7kN1s6rVodSZW8XFuavTYT0M5IErHaCqimRheh4gWKbd4SOQWl3C0ImpbE5yK3i3qH6/z03dWSoVVVfheuQ9rnz9p5qB08W5JnZknU2LgB1RN+Vd3bPYGwBtDF25jD8gbnz2tHKbZZ12gr4JrEw0MRHXcXhwifccEopnElFYh2fKHlrQ5bAzksBxspAQq65lOEeZgP8h7z8kSwsAOEmd6B4NSkJXDv1HS42GpZ2KXemdWSgCqL2xD9azLLrekIl09AJoY6J6sKPaLA2fGvFxgpQadRkThaqEaoMt+bWXXht4u5a3Ka/XyHYnRU8JTfq+EV44O9u5sT7P7bnjlmV9q6hSyfX9mUeQ+jQ0RUcdMDuhxLVs9G812tmQ5hMXh91kpqdT+M0QHh8oN8y8I2i8QYHMOTh6CvzhQaqqyc/N+hVTn0BSWj667T/RPcJlUIiHChqMHjPo/ReEiWJn9gESpm1rNrJAXEgT/8wGsZwTqiGyh3UTEyGB9L/1O+SnO1NPpG2YTO7j9w2oqYajtlK7pO8c4CA=
  file: "/home/travis/.m2/repository/ch/bbw/02_ConsoleCalculatorWithMaven/0.0.1-SNAPSHOT/02_ConsoleCalculatorWithMaven-0.0.1-SNAPSHOT.jar"
  on:
    repo: nicoYeet/ConsoleCalculatorWithMaven
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "nicoYeet"
      - git config --local user.email "nico.leemann@gmx.ch"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
    deploy:
      provider: releases
      api_key: "GITHUB OAUTH TOKEN"
      file: "FILE TO UPLOAD"
      skip_cleanup: true